name: synthetic_functions_generation_06
F1:
  amp: 3
  frec: 0.01
  interval: [0, 100]
  shift: -40
  char_to_plot: x
  color_to_plot: red
  train_num_samples: 3000
  test_num_samples: 500
F2:
  amp: 3
  frec: 0.01
  interval: [0, 100]
  shift: 10
  char_to_plot: o
  color_to_plot: green
  train_num_samples: 3000
  test_num_samples: 500
data:
  save: True
  plot: True
  normalize: True
  transformation: False
  train:
    path: ./data/synthetic_functions/train/06/
  test:
    path: ./data/synthetic_functions/test/06/
  plots:
    path: ./data/synthetic_functions/plots/06/
transformation:
  non_linear: sigmoid
  list_dimensions:
    - [10, 2]
    - [50, 10]
    - [100, 50]
